### ISSUE TITLE
Issue with Downloading after 5 chapters

### ISSUE THREAD

**Issue by UsamaWaheed** [MrHaCkEr/Wuxiaworld-2-eBook#10]
Hi,

Loved your program. Long time user.
I have seen that lately it no longer downloads after the first 5 chapters, and gives a HTTP not found error afterwards. I think Wuxia has implemented some type of safe guard. Can you kindly look into it?

Lastly, is there any way to show a progress bar & status bar at the bottom of GUI.
For example:
Status Bar: Downloading Chapter # 1 of Skyfire Avenue [where 1 is the actual number that is being downloaded]
Progress Bar: 1 - 100 % Green Bar

Thanks,
Usama

**Comment by MrHaCkEr** [comment]
Hm, what novel are you trying to download?

**Comment by UsamaWaheed** [comment]
Thanks for the fast reply. 

Initially I was trying with two novels BTTH & Skyfire Avenue. You mentioning the novel made me look at the link of the chapters and I saw in the Skyfire Avenue 758 - 765 and I saw that there are issues even on the website so that is not an issue with the program.

However, with BTTH let's say chapters 1550 to 1561, the program will download till 1555 (i.e. 6 chapters) and the python script will remain hung. Furthermore, this will happen for all the novels. For example TraXending Vision try chapter 60 to 70. 

Please let me know if you were able to re-produce the issue.

**Comment by jojkov** [comment]
Hello,
i tried downloading mentioned novels and chapters and all worked for me, except those Skyfire Avenue chapters. Tried latest version and it worked too.

**Comment by UsamaWaheed** [comment]
[Snagit.zip](https://github.com/MrHaCkEr/Wuxiaworld-2-eBook/files/1614560/Snagit.zip)
I am attaching two small videos for both BTTH & TraXending Vision. Maybe it can help you find the issue.

**Comment by UsamaWaheed** [comment]
I am attaching  a video while trying to download both BTTH & TraXending Vision chapters. Maybe it can help you find the issue.
[Issue.zip](https://github.com/MrHaCkEr/Wuxiaworld-2-eBook/files/1614589/Issue.zip)

**Comment by MrHaCkEr** [comment]
That is some odd bug. I can't replicate your problem using the current version on GitHub so I can only guess what's your problem is.
Here is a list with possible causes of your problem:

I noticed that the script is really slow on your pc. How is your internet speed? Could it be that you had a short timeout?

Check if you have all the dependencies installed. 

Did you try using the legacy console version (You can find the link in the readme or just change the branch)? TraXending Vision is not included but if it will fix your Issue you can add it yourself without much of a hassle.

Also what version of Python do you have installed?

**Comment by MrHaCkEr** [comment]
Skyfire avenue does not work because of link inconsistency. Will add a fix so the program will just ignore errors like this instead of crashing.
Will also add a progressbar.

**Comment by UsamaWaheed** [comment]
Thanks for the prompt response and really appreciate the help! 

With reference to your suggestions & queries, please find my responses as below:

- I tried using the console legacy version with the same output. Kindly note the console version used to work before without any issue at all. (This is true for all the novels not just TV or BTTH)

- My internet speed is at 20 Mpbs download and I get the same error in another place where the net is 100Mbps.

- Dependencies that I installed are BeautifulSoup4 & Pillow using the command line
   python -m pip install Pillow
   python -m pip install BeautifulSoup4
Let me know if I need to install some other library as well.

- Currently have Python 3.6.4 (32bit) installed on the PC.

Can you kindly share which exact version are you using so I can install and try it with that?

Thanks Again

**Comment by MrHaCkEr** [comment]
I'm running 3.6.3. but that should not be the problem. Also installing libraries using pip does not require the "python" prefix and -m is also not necessary in this case.

Since it seems to be a problem downloading the webpages the problem should be somewhere between line 19:29 in getify.py. I'd really like to help you but with me not being able to replicate the issue is makes this a little bit complicated.

So first I'd try out connecting to some free vpn service and trying it again. Make sure that you are not blocked on Wuxiaworld before trying it out though.

If that doesn't work you could try changing the header in line 25 of getify.py. Just use the User-Agent of the newest version of your Browser although I don't really have faith in that fix.

What would fix your problem with a high certainty, would be rewriting the whole function. The function is a lot more complicated than it needs to be and was just a preemptive measurement for circumventing basic anti-scraping implementations from Wuxiaworld. 
The question now is, do you have some basic Python knowledge? It should not be to hard. The function takes in the link and the name of the file as paramenters and downloads the page assosiated with the link. I could rewrite it myself but since I can't pinpoint the exact source of the problem I'd possible have to rewrite it a few times.

**Comment by UsamaWaheed** [comment]
I uninstalled Python 3.6.4 and went with Python 3.6.3 ( i know it wouldn't make difference but did that so I have a fresh installation). 

Furthermore, I tried changing the agent to my settings but to no avail. 

I am sorry not that good with Python so wouldn't be able to write the code. If it's possible and you are okay with it, I can share Teamviewer (remote desktop) session with you and you can check it out on my machine?

Thanks

**Comment by MrHaCkEr** [comment]
I guess I can take a look. I'm at uni right now, so I can't help you immediately.

How about you write me a E-Mail and send me your Discord username. We can talk when I'm @home.

**Comment by MrHaCkEr** [comment]
For some reason os.remove broke the code. If you come at the same problem, try removing line 62, 208 and 212-213 from getify.py
